[package]
authors = ["The Teaclave Authors"]
name = "sgx_types"
version = "1.1.4"
repository = "https://github.com/apache/teaclave-sgx-sdk"
license-file = "LICENSE"
documentation = "https://teaclave.apache.org/sgx-sdk-docs/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
edition = "2018"

[lib]
name = "sgx_types"

[features]
default = []
extra_traits = []

[dependencies]
